[package]
name = "chapter_19"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
migration = "0x0"
my_gov = "0x0"
my_market = "0x0"
